# Getting Started with NumPy: A Practical Guide

Welcome to this hands-on introduction to NumPy, a powerful Python library for numerical computing. In this notebook, we'll explore NumPy arrays, basic operations, and useful features to enhance performance and readability in your numerical code.

In [1]:
import numpy as np

## Performance Motivation

Let's compare a pure Python loop versus a NumPy vectorized operation for computing a dot product:

In [21]:
#Create arrays with 10 million random integers between 0 and 9
a = np.random.randint(0, 10, size=10_000_000)
b = np.random.randint(0, 10, size=10_000_000)

In [22]:
%%time
result = 0
for i in range(len(a)):
    result += a[i] * b[i]

CPU times: total: 8.53 s
Wall time: 9.37 s


In [23]:
%%time
result_np = np.dot(a, b)

CPU times: total: 31.2 ms
Wall time: 16.2 ms


## Creating Arrays
NumPy arrays are the foundation. Here's how you can create them:

In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2], [3, 4]])
print(arr1.shape)
print(arr2.shape)

(3,)
(2, 2)


## Array Initialization Shortcuts

In [10]:
print("A 2x3 matrix filled with zeros:")
print(np.zeros((2, 3)))

print("A 3x3 matrix filled with ones:")
print(np.ones((3, 3)))

print("A 4x4 identity matrix:")
print(np.eye(4))

A 2x3 matrix filled with zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
A 3x3 matrix filled with ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
A 4x4 identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Element-wise Operations

In [13]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("Element-wise addition of x and y:")
print(x + y)

print("Element-wise multiplication of x and y:")
print(x * y)

print("Apply the exponential function to each element in x:")
print(np.exp(x))

Element-wise addition of x and y:
[5 7 9]
Element-wise multiplication of x and y:
[ 4 10 18]
Apply the exponential function to each element in x:
[ 2.71828183  7.3890561  20.08553692]


## Matrix Multiplication and Reshaping

In [15]:
#Create a 2x2 matrix m1
m1 = np.array([[1, 2], [3, 4]])

#Create a 2x1 matrix m2
m2 = np.array([[5], [6]])

print("Matrix multiplication of m1 and m2 using the @ operator:")
print(m1 @ m2)

print("Reshape m1 into a single row (1x4) using reshape:")
print(m1.reshape((1, -1)))


Matrix multiplication of m1 and m2 using the @ operator:
[[17]
 [39]]
Reshape m1 into a single row (1x4) using reshape:
[[1 2 3 4]]


## Statistical Computations

In [17]:
data = np.array([[1, 2], [3, 4]])

print("Calculate the mean of all elements in the array:")
print(data.mean())

print("Calculate the standard deviation of all elements in the array:")
print(data.std())

print("Calculate the cumulative sum along the rows (axis=0):")
print(data.cumsum(axis=0))


Calculate the mean of all elements in the array:
2.5
Calculate the standard deviation of all elements in the array:
1.118033988749895
Calculate the cumulative sum along the rows (axis=0):
[[1 2]
 [4 6]]


## Indexing and Masking

In [19]:
z = np.array([5, 10, 15, 20])

print("Print elements from index 1 to 2 (slicing):")
print(z[1:3])

print("Print elements greater than 10 (boolean indexing):")
print(z[z > 10])

Print elements from index 1 to 2 (slicing):
[10 15]
Print elements greater than 10 (boolean indexing):
[15 20]


## Multi-dimensional Indexing

In [20]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])

print("Access the element at row 1, column 0:")
print(matrix[1, 0])

print("Access all elements in column 1:")
print(matrix[:, 1]) 

Access the element at row 1, column 0:
3
Access all elements in column 1:
[2 4 6]
